"""Initial migration after reset

Revision ID: d55620ec95d9
Revises: 
Create Date: 2024-06-17 19:19:53.914926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd55620ec95d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt', sa.Integer(), nullable=False))
        batch_op.drop_column('attemp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attemp', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('attempt')

    # ### end Alembic commands ###
